import pyjokes
import telebot
from googletrans import Translator
from dotenv import load_dotenv
import os


bot = telebot.TeleBot('5923409986:AAGh_or9NPf2wv_2DqI7BksTH3T2WMf9DQA')
load_dotenv()
COMICS = os.getenv('COMICS')
MILLENNIUM = os.getenv('MILLENNIUM')


def query_jokes(call):
    bot.answer_callback_query(callback_query_id=call.id)
    if call.data == 'joke':
        markup = telebot.types.InlineKeyboardMarkup()
        button1 = telebot.types.InlineKeyboardButton(text='Русский', callback_data='jokeru')
        button2 = telebot.types.InlineKeyboardButton(text='English', callback_data='jokeen')
        button3 = telebot.types.InlineKeyboardButton(text='Español', callback_data='jokees')
        button4 = telebot.types.InlineKeyboardButton(text='Deutsch', callback_data='jokede')
        button5 = telebot.types.InlineKeyboardButton(text='Шутки про Чака Норриса', callback_data='jokerunor')
        button6 = telebot.types.InlineKeyboardButton(text='Комикс "Весёлая дежурка"', callback_data='comics')
        button7 = telebot.types.InlineKeyboardButton(text="Назад", callback_data='main menu')
        markup.row(button1, button2)
        markup.row(button3, button4)
        markup.row(button5)
        markup.row(button6)
        markup.row(button7)
        bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        bot.send_message(call.message.chat.id,
                         '{0.first_name}, на каком языке Вы хотели бы порофлить и поорать '
                         'в голосяру?'.format(call.from_user, bot.get_me()), reply_markup=markup)
    elif call.data == 'joke2':
        markup = telebot.types.InlineKeyboardMarkup()
        button1 = telebot.types.InlineKeyboardButton(text='Русский', callback_data='jokeru')
        button2 = telebot.types.InlineKeyboardButton(text='English', callback_data='jokeen')
        button3 = telebot.types.InlineKeyboardButton(text='Español', callback_data='jokees')
        button4 = telebot.types.InlineKeyboardButton(text='Deutsch', callback_data='jokede')
        button5 = telebot.types.InlineKeyboardButton(text='Шутки про Чака Норриса', callback_data='jokerunor')
        button6 = telebot.types.InlineKeyboardButton(text='Комикс "Весёлая дежурка"', callback_data='comics')
        button7 = telebot.types.InlineKeyboardButton(text="Назад", callback_data='main menu')
        markup.row(button1, button2)
        markup.row(button3, button4)
        markup.row(button5)
        markup.row(button6)
        markup.row(button7)
        bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id, reply_markup=markup)
    elif call.data == 'jokeru':
        markup = telebot.types.InlineKeyboardMarkup()
        button1 = telebot.types.InlineKeyboardButton(text='Ещё шутку!', callback_data='jokeru')
        button2 = telebot.types.InlineKeyboardButton(text='Не смешно. Кнут.', callback_data='senior')
        button3 = telebot.types.InlineKeyboardButton(text="Назад", callback_data='joke2')
        markup.row(button1, button2)
        markup.row(button3)
        joke = pyjokes.get_joke()
        translator = Translator()
        joke_result = translator.translate(joke, 'ru')
        bot.send_message(call.message.chat.id, joke_result.text, reply_markup=markup)
    elif call.data == 'jokeen':
        markup = telebot.types.InlineKeyboardMarkup()
        button1 = telebot.types.InlineKeyboardButton(text='Ещё шутку!', callback_data='jokeen')
        button2 = telebot.types.InlineKeyboardButton(text='Не смешно. Кнут.', callback_data='senior')
        button3 = telebot.types.InlineKeyboardButton(text="Назад", callback_data='joke2')
        markup.row(button1, button2)
        markup.row(button3)
        joke = pyjokes.get_joke()
        bot.send_message(call.message.chat.id, joke, reply_markup=markup)
    elif call.data == 'jokees':
        markup = telebot.types.InlineKeyboardMarkup()
        button1 = telebot.types.InlineKeyboardButton(text='Ещё шутку!', callback_data='jokees')
        button2 = telebot.types.InlineKeyboardButton(text='Не смешно. Кнут.', callback_data='senior')
        button3 = telebot.types.InlineKeyboardButton(text="Назад", callback_data='joke2')
        markup.row(button1, button2)
        markup.row(button3)
        joke = pyjokes.get_joke('es')
        bot.send_message(call.message.chat.id, joke, reply_markup=markup)
    elif call.data == 'jokede':
        markup = telebot.types.InlineKeyboardMarkup()
        button1 = telebot.types.InlineKeyboardButton(text='Ещё шутку!', callback_data='jokede')
        button2 = telebot.types.InlineKeyboardButton(text='Не смешно. Кнут.', callback_data='senior')
        button3 = telebot.types.InlineKeyboardButton(text="Назад", callback_data='joke2')
        markup.row(button1, button2)
        markup.row(button3)
        joke = pyjokes.get_joke('de')
        bot.send_message(call.message.chat.id, joke, reply_markup=markup)
    elif call.data == 'jokerunor':
        markup = telebot.types.InlineKeyboardMarkup()
        button1 = telebot.types.InlineKeyboardButton(text='Ещё шутку!', callback_data='jokerunor')
        button2 = telebot.types.InlineKeyboardButton(text='Не смешно. Кнут.', callback_data='senior')
        button3 = telebot.types.InlineKeyboardButton(text="Назад", callback_data='joke2')
        markup.row(button1, button2)
        markup.row(button3)
        translator = Translator()
        joke = pyjokes.get_joke('en', 'chuck')
        joke_result = translator.translate(joke, 'ru')
        bot.send_message(call.message.chat.id, joke_result.text, reply_markup=markup)
    elif call.data == 'comics':
        markup = telebot.types.InlineKeyboardMarkup()
        button1 = telebot.types.InlineKeyboardButton(text='DS. Millennium (1997)', callback_data='millennium1')
        button2 = telebot.types.InlineKeyboardButton(text='Назад', callback_data='joke2')
        markup.row(button1)
        markup.row(button2)
        bot.send_message(call.message.chat.id, 'Выберите выпуск:', reply_markup=markup)
    elif call.data == 'millennium1':
        markup = telebot.types.InlineKeyboardMarkup()
        button1 = telebot.types.InlineKeyboardButton(text='Следующая глава', callback_data='millennium2')
        button2 = telebot.types.InlineKeyboardButton(text='Назад', callback_data='comics')
        markup.row(button1)
        markup.row(button2)
        bot.send_photo(call.message.chat.id, photo=open(MILLENNIUM + '1millennium.jpg', 'rb'), reply_markup=markup)
    elif call.data == 'millennium2':
        markup = telebot.types.InlineKeyboardMarkup()
        button1 = telebot.types.InlineKeyboardButton(text='Предыдущая глава', callback_data='millennium1')
        button2 = telebot.types.InlineKeyboardButton(text='Следующая глава', callback_data='millennium3')
        button3 = telebot.types.InlineKeyboardButton(text='Назад', callback_data='comics')
        markup.row(button1, button2)
        markup.row(button3)
        bot.send_photo(call.message.chat.id, photo=open(MILLENNIUM + '2millennium.jpg', 'rb'), reply_markup=markup)
    elif call.data == 'millennium3':
        markup = telebot.types.InlineKeyboardMarkup()
        button1 = telebot.types.InlineKeyboardButton(text='Предыдущая глава', callback_data='millennium1')
        button2 = telebot.types.InlineKeyboardButton(text='Назад', callback_data='comics')
        markup.row(button1)
        markup.row(button2)
        bot.send_photo(call.message.chat.id, photo=open(MILLENNIUM + '3millennium.jpg', 'rb'), reply_markup=markup)
